// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/messaging/messaging.proto

package messaging

import (
	whatsapp "github.com/usegro/proto/whatsapp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConversationStatus int32

const (
	ConversationStatus_CONV_OPEN     ConversationStatus = 0
	ConversationStatus_CONV_RESOLVED ConversationStatus = 1
	ConversationStatus_CONV_PENDING  ConversationStatus = 2
	ConversationStatus_CONV_SNOOZED  ConversationStatus = 3
)

// Enum value maps for ConversationStatus.
var (
	ConversationStatus_name = map[int32]string{
		0: "CONV_OPEN",
		1: "CONV_RESOLVED",
		2: "CONV_PENDING",
		3: "CONV_SNOOZED",
	}
	ConversationStatus_value = map[string]int32{
		"CONV_OPEN":     0,
		"CONV_RESOLVED": 1,
		"CONV_PENDING":  2,
		"CONV_SNOOZED":  3,
	}
)

func (x ConversationStatus) Enum() *ConversationStatus {
	p := new(ConversationStatus)
	*p = x
	return p
}

func (x ConversationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConversationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_messaging_messaging_proto_enumTypes[0].Descriptor()
}

func (ConversationStatus) Type() protoreflect.EnumType {
	return &file_proto_messaging_messaging_proto_enumTypes[0]
}

func (x ConversationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConversationStatus.Descriptor instead.
func (ConversationStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{0}
}

type MessageDirection int32

const (
	MessageDirection_DIRECTION_INBOUND  MessageDirection = 0
	MessageDirection_DIRECTION_OUTBOUND MessageDirection = 1
)

// Enum value maps for MessageDirection.
var (
	MessageDirection_name = map[int32]string{
		0: "DIRECTION_INBOUND",
		1: "DIRECTION_OUTBOUND",
	}
	MessageDirection_value = map[string]int32{
		"DIRECTION_INBOUND":  0,
		"DIRECTION_OUTBOUND": 1,
	}
)

func (x MessageDirection) Enum() *MessageDirection {
	p := new(MessageDirection)
	*p = x
	return p
}

func (x MessageDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_messaging_messaging_proto_enumTypes[1].Descriptor()
}

func (MessageDirection) Type() protoreflect.EnumType {
	return &file_proto_messaging_messaging_proto_enumTypes[1]
}

func (x MessageDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageDirection.Descriptor instead.
func (MessageDirection) EnumDescriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{1}
}

type TemplateStatus int32

const (
	TemplateStatus_TEMPLATE_PENDING  TemplateStatus = 0
	TemplateStatus_TEMPLATE_APPROVED TemplateStatus = 1
	TemplateStatus_TEMPLATE_REJECTED TemplateStatus = 2
)

// Enum value maps for TemplateStatus.
var (
	TemplateStatus_name = map[int32]string{
		0: "TEMPLATE_PENDING",
		1: "TEMPLATE_APPROVED",
		2: "TEMPLATE_REJECTED",
	}
	TemplateStatus_value = map[string]int32{
		"TEMPLATE_PENDING":  0,
		"TEMPLATE_APPROVED": 1,
		"TEMPLATE_REJECTED": 2,
	}
)

func (x TemplateStatus) Enum() *TemplateStatus {
	p := new(TemplateStatus)
	*p = x
	return p
}

func (x TemplateStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemplateStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_messaging_messaging_proto_enumTypes[2].Descriptor()
}

func (TemplateStatus) Type() protoreflect.EnumType {
	return &file_proto_messaging_messaging_proto_enumTypes[2]
}

func (x TemplateStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemplateStatus.Descriptor instead.
func (TemplateStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{2}
}

type CampaignStatus int32

const (
	CampaignStatus_CAMPAIGN_DRAFT     CampaignStatus = 0
	CampaignStatus_CAMPAIGN_SCHEDULED CampaignStatus = 1
	CampaignStatus_CAMPAIGN_RUNNING   CampaignStatus = 2
	CampaignStatus_CAMPAIGN_COMPLETED CampaignStatus = 3
	CampaignStatus_CAMPAIGN_FAILED    CampaignStatus = 4
)

// Enum value maps for CampaignStatus.
var (
	CampaignStatus_name = map[int32]string{
		0: "CAMPAIGN_DRAFT",
		1: "CAMPAIGN_SCHEDULED",
		2: "CAMPAIGN_RUNNING",
		3: "CAMPAIGN_COMPLETED",
		4: "CAMPAIGN_FAILED",
	}
	CampaignStatus_value = map[string]int32{
		"CAMPAIGN_DRAFT":     0,
		"CAMPAIGN_SCHEDULED": 1,
		"CAMPAIGN_RUNNING":   2,
		"CAMPAIGN_COMPLETED": 3,
		"CAMPAIGN_FAILED":    4,
	}
)

func (x CampaignStatus) Enum() *CampaignStatus {
	p := new(CampaignStatus)
	*p = x
	return p
}

func (x CampaignStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CampaignStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_messaging_messaging_proto_enumTypes[3].Descriptor()
}

func (CampaignStatus) Type() protoreflect.EnumType {
	return &file_proto_messaging_messaging_proto_enumTypes[3]
}

func (x CampaignStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CampaignStatus.Descriptor instead.
func (CampaignStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{3}
}

type Conversation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ContactId     string                 `protobuf:"bytes,3,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	ContactPhone  string                 `protobuf:"bytes,4,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	ContactName   string                 `protobuf:"bytes,5,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	Status        ConversationStatus     `protobuf:"varint,6,opt,name=status,proto3,enum=messaging.ConversationStatus" json:"status,omitempty"`
	AssignedTo    string                 `protobuf:"bytes,7,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"` // agent user_id
	Labels        []string               `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,9,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastMessageAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_message_at,json=lastMessageAt,proto3" json:"last_message_at,omitempty"`
	LastMessage   *Message               `protobuf:"bytes,12,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{0}
}

func (x *Conversation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Conversation) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Conversation) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *Conversation) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *Conversation) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *Conversation) GetStatus() ConversationStatus {
	if x != nil {
		return x.Status
	}
	return ConversationStatus_CONV_OPEN
}

func (x *Conversation) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *Conversation) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Conversation) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *Conversation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Conversation) GetLastMessageAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMessageAt
	}
	return nil
}

func (x *Conversation) GetLastMessage() *Message {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

type GetConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationRequest) Reset() {
	*x = GetConversationRequest{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationRequest) ProtoMessage() {}

func (x *GetConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationRequest.ProtoReflect.Descriptor instead.
func (*GetConversationRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{1}
}

func (x *GetConversationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AssignConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	AgentId        string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssignConversationRequest) Reset() {
	*x = AssignConversationRequest{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignConversationRequest) ProtoMessage() {}

func (x *AssignConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignConversationRequest.ProtoReflect.Descriptor instead.
func (*AssignConversationRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{2}
}

func (x *AssignConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *AssignConversationRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type LabelConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Labels         []string               `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LabelConversationRequest) Reset() {
	*x = LabelConversationRequest{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelConversationRequest) ProtoMessage() {}

func (x *LabelConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelConversationRequest.ProtoReflect.Descriptor instead.
func (*LabelConversationRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{3}
}

func (x *LabelConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *LabelConversationRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ResolveConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveConversationRequest) Reset() {
	*x = ResolveConversationRequest{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveConversationRequest) ProtoMessage() {}

func (x *ResolveConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveConversationRequest.ProtoReflect.Descriptor instead.
func (*ResolveConversationRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type ListConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        ConversationStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=messaging.ConversationStatus" json:"status,omitempty"`
	AssignedTo    string                 `protobuf:"bytes,3,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	Labels        []string               `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{5}
}

func (x *ListConversationsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListConversationsRequest) GetStatus() ConversationStatus {
	if x != nil {
		return x.Status
	}
	return ConversationStatus_CONV_OPEN
}

func (x *ListConversationsRequest) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *ListConversationsRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ListConversationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListConversationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*Conversation        `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResponse) Reset() {
	*x = ListConversationsResponse{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse) ProtoMessage() {}

func (x *ListConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{6}
}

func (x *ListConversationsResponse) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *ListConversationsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Message struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Id             string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId string                   `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	TenantId       string                   `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Direction      MessageDirection         `protobuf:"varint,4,opt,name=direction,proto3,enum=messaging.MessageDirection" json:"direction,omitempty"`
	Type           whatsapp.MessageType     `protobuf:"varint,5,opt,name=type,proto3,enum=whatsapp.MessageType" json:"type,omitempty"`
	Content        *whatsapp.MessageContent `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Status         whatsapp.MessageStatus   `protobuf:"varint,7,opt,name=status,proto3,enum=whatsapp.MessageStatus" json:"status,omitempty"`
	WaMessageId    string                   `protobuf:"bytes,8,opt,name=wa_message_id,json=waMessageId,proto3" json:"wa_message_id,omitempty"` // Meta's message ID
	CreatedAt      *timestamppb.Timestamp   `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{7}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Message) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Message) GetDirection() MessageDirection {
	if x != nil {
		return x.Direction
	}
	return MessageDirection_DIRECTION_INBOUND
}

func (x *Message) GetType() whatsapp.MessageType {
	if x != nil {
		return x.Type
	}
	return whatsapp.MessageType(0)
}

func (x *Message) GetContent() *whatsapp.MessageContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Message) GetStatus() whatsapp.MessageStatus {
	if x != nil {
		return x.Status
	}
	return whatsapp.MessageStatus(0)
}

func (x *Message) GetWaMessageId() string {
	if x != nil {
		return x.WaMessageId
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SendMessageRequest struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	ConversationId string                    `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	TenantId       string                    `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AgentId        string                    `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Content        *whatsapp.OutboundContent `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SendMessageRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SendMessageRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SendMessageRequest) GetContent() *whatsapp.OutboundContent {
	if x != nil {
		return x.Content
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	WaMessageId   string                 `protobuf:"bytes,2,opt,name=wa_message_id,json=waMessageId,proto3" json:"wa_message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{9}
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMessageResponse) GetWaMessageId() string {
	if x != nil {
		return x.WaMessageId
	}
	return ""
}

type ListMessagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Page           int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{10}
}

func (x *ListMessagesRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ListMessagesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMessagesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{11}
}

func (x *ListMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListMessagesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Template struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Language       string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Category       string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Status         TemplateStatus         `protobuf:"varint,6,opt,name=status,proto3,enum=messaging.TemplateStatus" json:"status,omitempty"`
	Components     []*TemplateComponent   `protobuf:"bytes,7,rep,name=components,proto3" json:"components,omitempty"`
	MetaTemplateId string                 `protobuf:"bytes,8,opt,name=meta_template_id,json=metaTemplateId,proto3" json:"meta_template_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{12}
}

func (x *Template) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Template) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Template) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Template) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Template) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Template) GetStatus() TemplateStatus {
	if x != nil {
		return x.Status
	}
	return TemplateStatus_TEMPLATE_PENDING
}

func (x *Template) GetComponents() []*TemplateComponent {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *Template) GetMetaTemplateId() string {
	if x != nil {
		return x.MetaTemplateId
	}
	return ""
}

func (x *Template) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type TemplateComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // HEADER, BODY, FOOTER, BUTTONS
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Buttons       []*TemplateButton      `protobuf:"bytes,3,rep,name=buttons,proto3" json:"buttons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateComponent) Reset() {
	*x = TemplateComponent{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateComponent) ProtoMessage() {}

func (x *TemplateComponent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateComponent.ProtoReflect.Descriptor instead.
func (*TemplateComponent) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{13}
}

func (x *TemplateComponent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TemplateComponent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TemplateComponent) GetButtons() []*TemplateButton {
	if x != nil {
		return x.Buttons
	}
	return nil
}

type TemplateButton struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // QUICK_REPLY, URL, PHONE_NUMBER
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateButton) Reset() {
	*x = TemplateButton{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateButton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateButton) ProtoMessage() {}

func (x *TemplateButton) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateButton.ProtoReflect.Descriptor instead.
func (*TemplateButton) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{14}
}

func (x *TemplateButton) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TemplateButton) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TemplateButton) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CreateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Components    []*TemplateComponent   `protobuf:"bytes,5,rep,name=components,proto3" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateRequest) Reset() {
	*x = CreateTemplateRequest{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateRequest) ProtoMessage() {}

func (x *CreateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{15}
}

func (x *CreateTemplateRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTemplateRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CreateTemplateRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateTemplateRequest) GetComponents() []*TemplateComponent {
	if x != nil {
		return x.Components
	}
	return nil
}

type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        TemplateStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=messaging.TemplateStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{16}
}

func (x *ListTemplatesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListTemplatesRequest) GetStatus() TemplateStatus {
	if x != nil {
		return x.Status
	}
	return TemplateStatus_TEMPLATE_PENDING
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*Template            `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{17}
}

func (x *ListTemplatesResponse) GetTemplates() []*Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

type SyncTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncTemplatesRequest) Reset() {
	*x = SyncTemplatesRequest{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTemplatesRequest) ProtoMessage() {}

func (x *SyncTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTemplatesRequest.ProtoReflect.Descriptor instead.
func (*SyncTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{18}
}

func (x *SyncTemplatesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type SyncTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Synced        int32                  `protobuf:"varint,1,opt,name=synced,proto3" json:"synced,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncTemplatesResponse) Reset() {
	*x = SyncTemplatesResponse{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTemplatesResponse) ProtoMessage() {}

func (x *SyncTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTemplatesResponse.ProtoReflect.Descriptor instead.
func (*SyncTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{19}
}

func (x *SyncTemplatesResponse) GetSynced() int32 {
	if x != nil {
		return x.Synced
	}
	return 0
}

type Campaign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	TemplateId    string                 `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Status        CampaignStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=messaging.CampaignStatus" json:"status,omitempty"`
	ContactIds    []string               `protobuf:"bytes,6,rep,name=contact_ids,json=contactIds,proto3" json:"contact_ids,omitempty"`          // or segment
	SegmentFilter string                 `protobuf:"bytes,7,opt,name=segment_filter,json=segmentFilter,proto3" json:"segment_filter,omitempty"` // JSON filter for dynamic segments
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{20}
}

func (x *Campaign) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Campaign) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Campaign) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Campaign) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *Campaign) GetStatus() CampaignStatus {
	if x != nil {
		return x.Status
	}
	return CampaignStatus_CAMPAIGN_DRAFT
}

func (x *Campaign) GetContactIds() []string {
	if x != nil {
		return x.ContactIds
	}
	return nil
}

func (x *Campaign) GetSegmentFilter() string {
	if x != nil {
		return x.SegmentFilter
	}
	return ""
}

func (x *Campaign) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *Campaign) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *Campaign) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CampaignStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Sent          int32                  `protobuf:"varint,3,opt,name=sent,proto3" json:"sent,omitempty"`
	Delivered     int32                  `protobuf:"varint,4,opt,name=delivered,proto3" json:"delivered,omitempty"`
	Read          int32                  `protobuf:"varint,5,opt,name=read,proto3" json:"read,omitempty"`
	Replied       int32                  `protobuf:"varint,6,opt,name=replied,proto3" json:"replied,omitempty"`
	Failed        int32                  `protobuf:"varint,7,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignStats) Reset() {
	*x = CampaignStats{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignStats) ProtoMessage() {}

func (x *CampaignStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignStats.ProtoReflect.Descriptor instead.
func (*CampaignStats) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{21}
}

func (x *CampaignStats) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *CampaignStats) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CampaignStats) GetSent() int32 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *CampaignStats) GetDelivered() int32 {
	if x != nil {
		return x.Delivered
	}
	return 0
}

func (x *CampaignStats) GetRead() int32 {
	if x != nil {
		return x.Read
	}
	return 0
}

func (x *CampaignStats) GetReplied() int32 {
	if x != nil {
		return x.Replied
	}
	return 0
}

func (x *CampaignStats) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

type CreateCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TemplateId    string                 `protobuf:"bytes,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	ContactIds    []string               `protobuf:"bytes,4,rep,name=contact_ids,json=contactIds,proto3" json:"contact_ids,omitempty"`
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignRequest) Reset() {
	*x = CreateCampaignRequest{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignRequest) ProtoMessage() {}

func (x *CreateCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignRequest.ProtoReflect.Descriptor instead.
func (*CreateCampaignRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{22}
}

func (x *CreateCampaignRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateCampaignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCampaignRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CreateCampaignRequest) GetContactIds() []string {
	if x != nil {
		return x.ContactIds
	}
	return nil
}

func (x *CreateCampaignRequest) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

type LaunchCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchCampaignRequest) Reset() {
	*x = LaunchCampaignRequest{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchCampaignRequest) ProtoMessage() {}

func (x *LaunchCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchCampaignRequest.ProtoReflect.Descriptor instead.
func (*LaunchCampaignRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{23}
}

func (x *LaunchCampaignRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

type GetCampaignStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignStatsRequest) Reset() {
	*x = GetCampaignStatsRequest{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignStatsRequest) ProtoMessage() {}

func (x *GetCampaignStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignStatsRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{24}
}

func (x *GetCampaignStatsRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

var File_proto_messaging_messaging_proto protoreflect.FileDescriptor

const file_proto_messaging_messaging_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/messaging/messaging.proto\x12\tmessaging\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dproto/whatsapp/whatsapp.proto\"\xeb\x03\n" +
	"\fConversation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x03 \x01(\tR\tcontactId\x12#\n" +
	"\rcontact_phone\x18\x04 \x01(\tR\fcontactPhone\x12!\n" +
	"\fcontact_name\x18\x05 \x01(\tR\vcontactName\x125\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1d.messaging.ConversationStatusR\x06status\x12\x1f\n" +
	"\vassigned_to\x18\a \x01(\tR\n" +
	"assignedTo\x12\x16\n" +
	"\x06labels\x18\b \x03(\tR\x06labels\x12!\n" +
	"\funread_count\x18\t \x01(\x05R\vunreadCount\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12B\n" +
	"\x0flast_message_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\rlastMessageAt\x125\n" +
	"\flast_message\x18\f \x01(\v2\x12.messaging.MessageR\vlastMessage\"(\n" +
	"\x16GetConversationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"_\n" +
	"\x19AssignConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\"[\n" +
	"\x18LabelConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\tR\x06labels\"E\n" +
	"\x1aResolveConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"\xd8\x01\n" +
	"\x18ListConversationsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.messaging.ConversationStatusR\x06status\x12\x1f\n" +
	"\vassigned_to\x18\x03 \x01(\tR\n" +
	"assignedTo\x12\x16\n" +
	"\x06labels\x18\x04 \x03(\tR\x06labels\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"p\n" +
	"\x19ListConversationsResponse\x12=\n" +
	"\rconversations\x18\x01 \x03(\v2\x17.messaging.ConversationR\rconversations\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x89\x03\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x129\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x1b.messaging.MessageDirectionR\tdirection\x12)\n" +
	"\x04type\x18\x05 \x01(\x0e2\x15.whatsapp.MessageTypeR\x04type\x122\n" +
	"\acontent\x18\x06 \x01(\v2\x18.whatsapp.MessageContentR\acontent\x12/\n" +
	"\x06status\x18\a \x01(\x0e2\x17.whatsapp.MessageStatusR\x06status\x12\"\n" +
	"\rwa_message_id\x18\b \x01(\tR\vwaMessageId\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xaa\x01\n" +
	"\x12SendMessageRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x123\n" +
	"\acontent\x18\x04 \x01(\v2\x19.whatsapp.OutboundContentR\acontent\"X\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\"\n" +
	"\rwa_message_id\x18\x02 \x01(\tR\vwaMessageId\"o\n" +
	"\x13ListMessagesRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\\\n" +
	"\x14ListMessagesResponse\x12.\n" +
	"\bmessages\x18\x01 \x03(\v2\x12.messaging.MessageR\bmessages\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xd9\x02\n" +
	"\bTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x121\n" +
	"\x06status\x18\x06 \x01(\x0e2\x19.messaging.TemplateStatusR\x06status\x12<\n" +
	"\n" +
	"components\x18\a \x03(\v2\x1c.messaging.TemplateComponentR\n" +
	"components\x12(\n" +
	"\x10meta_template_id\x18\b \x01(\tR\x0emetaTemplateId\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"p\n" +
	"\x11TemplateComponent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x123\n" +
	"\abuttons\x18\x03 \x03(\v2\x19.messaging.TemplateButtonR\abuttons\"N\n" +
	"\x0eTemplateButton\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\xbe\x01\n" +
	"\x15CreateTemplateRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12<\n" +
	"\n" +
	"components\x18\x05 \x03(\v2\x1c.messaging.TemplateComponentR\n" +
	"components\"f\n" +
	"\x14ListTemplatesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.messaging.TemplateStatusR\x06status\"J\n" +
	"\x15ListTemplatesResponse\x121\n" +
	"\ttemplates\x18\x01 \x03(\v2\x13.messaging.TemplateR\ttemplates\"3\n" +
	"\x14SyncTemplatesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"/\n" +
	"\x15SyncTemplatesResponse\x12\x16\n" +
	"\x06synced\x18\x01 \x01(\x05R\x06synced\"\x96\x03\n" +
	"\bCampaign\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vtemplate_id\x18\x04 \x01(\tR\n" +
	"templateId\x121\n" +
	"\x06status\x18\x05 \x01(\x0e2\x19.messaging.CampaignStatusR\x06status\x12\x1f\n" +
	"\vcontact_ids\x18\x06 \x03(\tR\n" +
	"contactIds\x12%\n" +
	"\x0esegment_filter\x18\a \x01(\tR\rsegmentFilter\x12=\n" +
	"\fscheduled_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x123\n" +
	"\asent_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xbe\x01\n" +
	"\rCampaignStats\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04sent\x18\x03 \x01(\x05R\x04sent\x12\x1c\n" +
	"\tdelivered\x18\x04 \x01(\x05R\tdelivered\x12\x12\n" +
	"\x04read\x18\x05 \x01(\x05R\x04read\x12\x18\n" +
	"\areplied\x18\x06 \x01(\x05R\areplied\x12\x16\n" +
	"\x06failed\x18\a \x01(\x05R\x06failed\"\xc9\x01\n" +
	"\x15CreateCampaignRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vtemplate_id\x18\x03 \x01(\tR\n" +
	"templateId\x12\x1f\n" +
	"\vcontact_ids\x18\x04 \x03(\tR\n" +
	"contactIds\x12=\n" +
	"\fscheduled_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\"8\n" +
	"\x15LaunchCampaignRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\":\n" +
	"\x17GetCampaignStatsRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId*Z\n" +
	"\x12ConversationStatus\x12\r\n" +
	"\tCONV_OPEN\x10\x00\x12\x11\n" +
	"\rCONV_RESOLVED\x10\x01\x12\x10\n" +
	"\fCONV_PENDING\x10\x02\x12\x10\n" +
	"\fCONV_SNOOZED\x10\x03*A\n" +
	"\x10MessageDirection\x12\x15\n" +
	"\x11DIRECTION_INBOUND\x10\x00\x12\x16\n" +
	"\x12DIRECTION_OUTBOUND\x10\x01*T\n" +
	"\x0eTemplateStatus\x12\x14\n" +
	"\x10TEMPLATE_PENDING\x10\x00\x12\x15\n" +
	"\x11TEMPLATE_APPROVED\x10\x01\x12\x15\n" +
	"\x11TEMPLATE_REJECTED\x10\x02*\x7f\n" +
	"\x0eCampaignStatus\x12\x12\n" +
	"\x0eCAMPAIGN_DRAFT\x10\x00\x12\x16\n" +
	"\x12CAMPAIGN_SCHEDULED\x10\x01\x12\x14\n" +
	"\x10CAMPAIGN_RUNNING\x10\x02\x12\x16\n" +
	"\x12CAMPAIGN_COMPLETED\x10\x03\x12\x13\n" +
	"\x0fCAMPAIGN_FAILED\x10\x042\xbc\b\n" +
	"\x10MessagingService\x12M\n" +
	"\x0fGetConversation\x12!.messaging.GetConversationRequest\x1a\x17.messaging.Conversation\x12^\n" +
	"\x11ListConversations\x12#.messaging.ListConversationsRequest\x1a$.messaging.ListConversationsResponse\x12S\n" +
	"\x12AssignConversation\x12$.messaging.AssignConversationRequest\x1a\x17.messaging.Conversation\x12Q\n" +
	"\x11LabelConversation\x12#.messaging.LabelConversationRequest\x1a\x17.messaging.Conversation\x12U\n" +
	"\x13ResolveConversation\x12%.messaging.ResolveConversationRequest\x1a\x17.messaging.Conversation\x12L\n" +
	"\vSendMessage\x12\x1d.messaging.SendMessageRequest\x1a\x1e.messaging.SendMessageResponse\x12O\n" +
	"\fListMessages\x12\x1e.messaging.ListMessagesRequest\x1a\x1f.messaging.ListMessagesResponse\x12G\n" +
	"\x0eCreateTemplate\x12 .messaging.CreateTemplateRequest\x1a\x13.messaging.Template\x12R\n" +
	"\rListTemplates\x12\x1f.messaging.ListTemplatesRequest\x1a .messaging.ListTemplatesResponse\x12Z\n" +
	"\x15SyncTemplatesFromMeta\x12\x1f.messaging.SyncTemplatesRequest\x1a .messaging.SyncTemplatesResponse\x12G\n" +
	"\x0eCreateCampaign\x12 .messaging.CreateCampaignRequest\x1a\x13.messaging.Campaign\x12G\n" +
	"\x0eLaunchCampaign\x12 .messaging.LaunchCampaignRequest\x1a\x13.messaging.Campaign\x12P\n" +
	"\x10GetCampaignStats\x12\".messaging.GetCampaignStatsRequest\x1a\x18.messaging.CampaignStatsB#Z!github.com/usegro/proto/messagingb\x06proto3"

var (
	file_proto_messaging_messaging_proto_rawDescOnce sync.Once
	file_proto_messaging_messaging_proto_rawDescData []byte
)

func file_proto_messaging_messaging_proto_rawDescGZIP() []byte {
	file_proto_messaging_messaging_proto_rawDescOnce.Do(func() {
		file_proto_messaging_messaging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messaging_messaging_proto_rawDesc), len(file_proto_messaging_messaging_proto_rawDesc)))
	})
	return file_proto_messaging_messaging_proto_rawDescData
}

var file_proto_messaging_messaging_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_messaging_messaging_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_messaging_messaging_proto_goTypes = []any{
	(ConversationStatus)(0),            // 0: messaging.ConversationStatus
	(MessageDirection)(0),              // 1: messaging.MessageDirection
	(TemplateStatus)(0),                // 2: messaging.TemplateStatus
	(CampaignStatus)(0),                // 3: messaging.CampaignStatus
	(*Conversation)(nil),               // 4: messaging.Conversation
	(*GetConversationRequest)(nil),     // 5: messaging.GetConversationRequest
	(*AssignConversationRequest)(nil),  // 6: messaging.AssignConversationRequest
	(*LabelConversationRequest)(nil),   // 7: messaging.LabelConversationRequest
	(*ResolveConversationRequest)(nil), // 8: messaging.ResolveConversationRequest
	(*ListConversationsRequest)(nil),   // 9: messaging.ListConversationsRequest
	(*ListConversationsResponse)(nil),  // 10: messaging.ListConversationsResponse
	(*Message)(nil),                    // 11: messaging.Message
	(*SendMessageRequest)(nil),         // 12: messaging.SendMessageRequest
	(*SendMessageResponse)(nil),        // 13: messaging.SendMessageResponse
	(*ListMessagesRequest)(nil),        // 14: messaging.ListMessagesRequest
	(*ListMessagesResponse)(nil),       // 15: messaging.ListMessagesResponse
	(*Template)(nil),                   // 16: messaging.Template
	(*TemplateComponent)(nil),          // 17: messaging.TemplateComponent
	(*TemplateButton)(nil),             // 18: messaging.TemplateButton
	(*CreateTemplateRequest)(nil),      // 19: messaging.CreateTemplateRequest
	(*ListTemplatesRequest)(nil),       // 20: messaging.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),      // 21: messaging.ListTemplatesResponse
	(*SyncTemplatesRequest)(nil),       // 22: messaging.SyncTemplatesRequest
	(*SyncTemplatesResponse)(nil),      // 23: messaging.SyncTemplatesResponse
	(*Campaign)(nil),                   // 24: messaging.Campaign
	(*CampaignStats)(nil),              // 25: messaging.CampaignStats
	(*CreateCampaignRequest)(nil),      // 26: messaging.CreateCampaignRequest
	(*LaunchCampaignRequest)(nil),      // 27: messaging.LaunchCampaignRequest
	(*GetCampaignStatsRequest)(nil),    // 28: messaging.GetCampaignStatsRequest
	(*timestamppb.Timestamp)(nil),      // 29: google.protobuf.Timestamp
	(whatsapp.MessageType)(0),          // 30: whatsapp.MessageType
	(*whatsapp.MessageContent)(nil),    // 31: whatsapp.MessageContent
	(whatsapp.MessageStatus)(0),        // 32: whatsapp.MessageStatus
	(*whatsapp.OutboundContent)(nil),   // 33: whatsapp.OutboundContent
}
var file_proto_messaging_messaging_proto_depIdxs = []int32{
	0,  // 0: messaging.Conversation.status:type_name -> messaging.ConversationStatus
	29, // 1: messaging.Conversation.created_at:type_name -> google.protobuf.Timestamp
	29, // 2: messaging.Conversation.last_message_at:type_name -> google.protobuf.Timestamp
	11, // 3: messaging.Conversation.last_message:type_name -> messaging.Message
	0,  // 4: messaging.ListConversationsRequest.status:type_name -> messaging.ConversationStatus
	4,  // 5: messaging.ListConversationsResponse.conversations:type_name -> messaging.Conversation
	1,  // 6: messaging.Message.direction:type_name -> messaging.MessageDirection
	30, // 7: messaging.Message.type:type_name -> whatsapp.MessageType
	31, // 8: messaging.Message.content:type_name -> whatsapp.MessageContent
	32, // 9: messaging.Message.status:type_name -> whatsapp.MessageStatus
	29, // 10: messaging.Message.created_at:type_name -> google.protobuf.Timestamp
	33, // 11: messaging.SendMessageRequest.content:type_name -> whatsapp.OutboundContent
	11, // 12: messaging.ListMessagesResponse.messages:type_name -> messaging.Message
	2,  // 13: messaging.Template.status:type_name -> messaging.TemplateStatus
	17, // 14: messaging.Template.components:type_name -> messaging.TemplateComponent
	29, // 15: messaging.Template.created_at:type_name -> google.protobuf.Timestamp
	18, // 16: messaging.TemplateComponent.buttons:type_name -> messaging.TemplateButton
	17, // 17: messaging.CreateTemplateRequest.components:type_name -> messaging.TemplateComponent
	2,  // 18: messaging.ListTemplatesRequest.status:type_name -> messaging.TemplateStatus
	16, // 19: messaging.ListTemplatesResponse.templates:type_name -> messaging.Template
	3,  // 20: messaging.Campaign.status:type_name -> messaging.CampaignStatus
	29, // 21: messaging.Campaign.scheduled_at:type_name -> google.protobuf.Timestamp
	29, // 22: messaging.Campaign.sent_at:type_name -> google.protobuf.Timestamp
	29, // 23: messaging.Campaign.created_at:type_name -> google.protobuf.Timestamp
	29, // 24: messaging.CreateCampaignRequest.scheduled_at:type_name -> google.protobuf.Timestamp
	5,  // 25: messaging.MessagingService.GetConversation:input_type -> messaging.GetConversationRequest
	9,  // 26: messaging.MessagingService.ListConversations:input_type -> messaging.ListConversationsRequest
	6,  // 27: messaging.MessagingService.AssignConversation:input_type -> messaging.AssignConversationRequest
	7,  // 28: messaging.MessagingService.LabelConversation:input_type -> messaging.LabelConversationRequest
	8,  // 29: messaging.MessagingService.ResolveConversation:input_type -> messaging.ResolveConversationRequest
	12, // 30: messaging.MessagingService.SendMessage:input_type -> messaging.SendMessageRequest
	14, // 31: messaging.MessagingService.ListMessages:input_type -> messaging.ListMessagesRequest
	19, // 32: messaging.MessagingService.CreateTemplate:input_type -> messaging.CreateTemplateRequest
	20, // 33: messaging.MessagingService.ListTemplates:input_type -> messaging.ListTemplatesRequest
	22, // 34: messaging.MessagingService.SyncTemplatesFromMeta:input_type -> messaging.SyncTemplatesRequest
	26, // 35: messaging.MessagingService.CreateCampaign:input_type -> messaging.CreateCampaignRequest
	27, // 36: messaging.MessagingService.LaunchCampaign:input_type -> messaging.LaunchCampaignRequest
	28, // 37: messaging.MessagingService.GetCampaignStats:input_type -> messaging.GetCampaignStatsRequest
	4,  // 38: messaging.MessagingService.GetConversation:output_type -> messaging.Conversation
	10, // 39: messaging.MessagingService.ListConversations:output_type -> messaging.ListConversationsResponse
	4,  // 40: messaging.MessagingService.AssignConversation:output_type -> messaging.Conversation
	4,  // 41: messaging.MessagingService.LabelConversation:output_type -> messaging.Conversation
	4,  // 42: messaging.MessagingService.ResolveConversation:output_type -> messaging.Conversation
	13, // 43: messaging.MessagingService.SendMessage:output_type -> messaging.SendMessageResponse
	15, // 44: messaging.MessagingService.ListMessages:output_type -> messaging.ListMessagesResponse
	16, // 45: messaging.MessagingService.CreateTemplate:output_type -> messaging.Template
	21, // 46: messaging.MessagingService.ListTemplates:output_type -> messaging.ListTemplatesResponse
	23, // 47: messaging.MessagingService.SyncTemplatesFromMeta:output_type -> messaging.SyncTemplatesResponse
	24, // 48: messaging.MessagingService.CreateCampaign:output_type -> messaging.Campaign
	24, // 49: messaging.MessagingService.LaunchCampaign:output_type -> messaging.Campaign
	25, // 50: messaging.MessagingService.GetCampaignStats:output_type -> messaging.CampaignStats
	38, // [38:51] is the sub-list for method output_type
	25, // [25:38] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_proto_messaging_messaging_proto_init() }
func file_proto_messaging_messaging_proto_init() {
	if File_proto_messaging_messaging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messaging_messaging_proto_rawDesc), len(file_proto_messaging_messaging_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_messaging_messaging_proto_goTypes,
		DependencyIndexes: file_proto_messaging_messaging_proto_depIdxs,
		EnumInfos:         file_proto_messaging_messaging_proto_enumTypes,
		MessageInfos:      file_proto_messaging_messaging_proto_msgTypes,
	}.Build()
	File_proto_messaging_messaging_proto = out.File
	file_proto_messaging_messaging_proto_goTypes = nil
	file_proto_messaging_messaging_proto_depIdxs = nil
}
