// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/whatsapp/whatsapp.proto

package whatsapp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageStatus int32

const (
	MessageStatus_STATUS_UNKNOWN   MessageStatus = 0
	MessageStatus_STATUS_SENT      MessageStatus = 1
	MessageStatus_STATUS_DELIVERED MessageStatus = 2
	MessageStatus_STATUS_READ      MessageStatus = 3
	MessageStatus_STATUS_FAILED    MessageStatus = 4
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_SENT",
		2: "STATUS_DELIVERED",
		3: "STATUS_READ",
		4: "STATUS_FAILED",
	}
	MessageStatus_value = map[string]int32{
		"STATUS_UNKNOWN":   0,
		"STATUS_SENT":      1,
		"STATUS_DELIVERED": 2,
		"STATUS_READ":      3,
		"STATUS_FAILED":    4,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_whatsapp_whatsapp_proto_enumTypes[0].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_proto_whatsapp_whatsapp_proto_enumTypes[0]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_TYPE_UNKNOWN     MessageType = 0
	MessageType_TYPE_TEXT        MessageType = 1
	MessageType_TYPE_IMAGE       MessageType = 2
	MessageType_TYPE_VIDEO       MessageType = 3
	MessageType_TYPE_AUDIO       MessageType = 4
	MessageType_TYPE_DOCUMENT    MessageType = 5
	MessageType_TYPE_LOCATION    MessageType = 6
	MessageType_TYPE_CONTACTS    MessageType = 7
	MessageType_TYPE_INTERACTIVE MessageType = 8
	MessageType_TYPE_BUTTON      MessageType = 9
	MessageType_TYPE_STICKER     MessageType = 10
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "TYPE_UNKNOWN",
		1:  "TYPE_TEXT",
		2:  "TYPE_IMAGE",
		3:  "TYPE_VIDEO",
		4:  "TYPE_AUDIO",
		5:  "TYPE_DOCUMENT",
		6:  "TYPE_LOCATION",
		7:  "TYPE_CONTACTS",
		8:  "TYPE_INTERACTIVE",
		9:  "TYPE_BUTTON",
		10: "TYPE_STICKER",
	}
	MessageType_value = map[string]int32{
		"TYPE_UNKNOWN":     0,
		"TYPE_TEXT":        1,
		"TYPE_IMAGE":       2,
		"TYPE_VIDEO":       3,
		"TYPE_AUDIO":       4,
		"TYPE_DOCUMENT":    5,
		"TYPE_LOCATION":    6,
		"TYPE_CONTACTS":    7,
		"TYPE_INTERACTIVE": 8,
		"TYPE_BUTTON":      9,
		"TYPE_STICKER":     10,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_whatsapp_whatsapp_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_whatsapp_whatsapp_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{1}
}

type InboundMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	WabaId        string                 `protobuf:"bytes,2,opt,name=waba_id,json=wabaId,proto3" json:"waba_id,omitempty"` // which tenant's WABA
	PhoneNumberId string                 `protobuf:"bytes,3,opt,name=phone_number_id,json=phoneNumberId,proto3" json:"phone_number_id,omitempty"`
	From          string                 `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"` // sender's phone number
	To            string                 `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	Type          MessageType            `protobuf:"varint,6,opt,name=type,proto3,enum=whatsapp.MessageType" json:"type,omitempty"`
	Content       *MessageContent        `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Contact       *Contact               `protobuf:"bytes,9,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundMessage) Reset() {
	*x = InboundMessage{}
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundMessage) ProtoMessage() {}

func (x *InboundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundMessage.ProtoReflect.Descriptor instead.
func (*InboundMessage) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{0}
}

func (x *InboundMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *InboundMessage) GetWabaId() string {
	if x != nil {
		return x.WabaId
	}
	return ""
}

func (x *InboundMessage) GetPhoneNumberId() string {
	if x != nil {
		return x.PhoneNumberId
	}
	return ""
}

func (x *InboundMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *InboundMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *InboundMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_TYPE_UNKNOWN
}

func (x *InboundMessage) GetContent() *MessageContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *InboundMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *InboundMessage) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

type MessageContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*MessageContent_Text
	//	*MessageContent_Media
	//	*MessageContent_Location
	//	*MessageContent_Interactive
	//	*MessageContent_Button
	Value         isMessageContent_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageContent) Reset() {
	*x = MessageContent{}
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContent) ProtoMessage() {}

func (x *MessageContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContent.ProtoReflect.Descriptor instead.
func (*MessageContent) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{1}
}

func (x *MessageContent) GetValue() isMessageContent_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MessageContent) GetText() *TextMessage {
	if x != nil {
		if x, ok := x.Value.(*MessageContent_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *MessageContent) GetMedia() *MediaMessage {
	if x != nil {
		if x, ok := x.Value.(*MessageContent_Media); ok {
			return x.Media
		}
	}
	return nil
}

func (x *MessageContent) GetLocation() *LocationMessage {
	if x != nil {
		if x, ok := x.Value.(*MessageContent_Location); ok {
			return x.Location
		}
	}
	return nil
}

func (x *MessageContent) GetInteractive() *InteractiveReply {
	if x != nil {
		if x, ok := x.Value.(*MessageContent_Interactive); ok {
			return x.Interactive
		}
	}
	return nil
}

func (x *MessageContent) GetButton() *ButtonReply {
	if x != nil {
		if x, ok := x.Value.(*MessageContent_Button); ok {
			return x.Button
		}
	}
	return nil
}

type isMessageContent_Value interface {
	isMessageContent_Value()
}

type MessageContent_Text struct {
	Text *TextMessage `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type MessageContent_Media struct {
	Media *MediaMessage `protobuf:"bytes,2,opt,name=media,proto3,oneof"`
}

type MessageContent_Location struct {
	Location *LocationMessage `protobuf:"bytes,3,opt,name=location,proto3,oneof"`
}

type MessageContent_Interactive struct {
	Interactive *InteractiveReply `protobuf:"bytes,4,opt,name=interactive,proto3,oneof"`
}

type MessageContent_Button struct {
	Button *ButtonReply `protobuf:"bytes,5,opt,name=button,proto3,oneof"`
}

func (*MessageContent_Text) isMessageContent_Value() {}

func (*MessageContent_Media) isMessageContent_Value() {}

func (*MessageContent_Location) isMessageContent_Value() {}

func (*MessageContent_Interactive) isMessageContent_Value() {}

func (*MessageContent_Button) isMessageContent_Value() {}

type TextMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextMessage) Reset() {
	*x = TextMessage{}
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextMessage) ProtoMessage() {}

func (x *TextMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextMessage.ProtoReflect.Descriptor instead.
func (*TextMessage) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{2}
}

func (x *TextMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type MediaMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Caption       string                 `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	Filename      string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"` // documents only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaMessage) Reset() {
	*x = MediaMessage{}
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaMessage) ProtoMessage() {}

func (x *MediaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaMessage.ProtoReflect.Descriptor instead.
func (*MediaMessage) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{3}
}

func (x *MediaMessage) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *MediaMessage) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *MediaMessage) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *MediaMessage) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *MediaMessage) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type LocationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationMessage) Reset() {
	*x = LocationMessage{}
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationMessage) ProtoMessage() {}

func (x *LocationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationMessage.ProtoReflect.Descriptor instead.
func (*LocationMessage) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{4}
}

func (x *LocationMessage) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationMessage) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LocationMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LocationMessage) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type InteractiveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractiveReply) Reset() {
	*x = InteractiveReply{}
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractiveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractiveReply) ProtoMessage() {}

func (x *InteractiveReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractiveReply.ProtoReflect.Descriptor instead.
func (*InteractiveReply) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{5}
}

func (x *InteractiveReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InteractiveReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InteractiveReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ButtonReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ButtonReply) Reset() {
	*x = ButtonReply{}
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ButtonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButtonReply) ProtoMessage() {}

func (x *ButtonReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButtonReply.ProtoReflect.Descriptor instead.
func (*ButtonReply) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{6}
}

func (x *ButtonReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ButtonReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaId          string                 `protobuf:"bytes,1,opt,name=wa_id,json=waId,proto3" json:"wa_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{7}
}

func (x *Contact) GetWaId() string {
	if x != nil {
		return x.WaId
	}
	return ""
}

func (x *Contact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type OutboundMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	To             string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	PhoneNumberId  string                 `protobuf:"bytes,2,opt,name=phone_number_id,json=phoneNumberId,proto3" json:"phone_number_id,omitempty"`
	WabaId         string                 `protobuf:"bytes,3,opt,name=waba_id,json=wabaId,proto3" json:"waba_id,omitempty"`
	Content        *OutboundContent       `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // prevent duplicate sends
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OutboundMessage) Reset() {
	*x = OutboundMessage{}
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundMessage) ProtoMessage() {}

func (x *OutboundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundMessage.ProtoReflect.Descriptor instead.
func (*OutboundMessage) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{8}
}

func (x *OutboundMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *OutboundMessage) GetPhoneNumberId() string {
	if x != nil {
		return x.PhoneNumberId
	}
	return ""
}

func (x *OutboundMessage) GetWabaId() string {
	if x != nil {
		return x.WabaId
	}
	return ""
}

func (x *OutboundMessage) GetContent() *OutboundContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *OutboundMessage) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type OutboundContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*OutboundContent_Text
	//	*OutboundContent_Template
	//	*OutboundContent_Media
	//	*OutboundContent_Interactive
	Value         isOutboundContent_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundContent) Reset() {
	*x = OutboundContent{}
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundContent) ProtoMessage() {}

func (x *OutboundContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundContent.ProtoReflect.Descriptor instead.
func (*OutboundContent) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{9}
}

func (x *OutboundContent) GetValue() isOutboundContent_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *OutboundContent) GetText() *TextMessage {
	if x != nil {
		if x, ok := x.Value.(*OutboundContent_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *OutboundContent) GetTemplate() *TemplateMessage {
	if x != nil {
		if x, ok := x.Value.(*OutboundContent_Template); ok {
			return x.Template
		}
	}
	return nil
}

func (x *OutboundContent) GetMedia() *MediaMessage {
	if x != nil {
		if x, ok := x.Value.(*OutboundContent_Media); ok {
			return x.Media
		}
	}
	return nil
}

func (x *OutboundContent) GetInteractive() *InteractiveMessage {
	if x != nil {
		if x, ok := x.Value.(*OutboundContent_Interactive); ok {
			return x.Interactive
		}
	}
	return nil
}

type isOutboundContent_Value interface {
	isOutboundContent_Value()
}

type OutboundContent_Text struct {
	Text *TextMessage `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type OutboundContent_Template struct {
	Template *TemplateMessage `protobuf:"bytes,2,opt,name=template,proto3,oneof"`
}

type OutboundContent_Media struct {
	Media *MediaMessage `protobuf:"bytes,3,opt,name=media,proto3,oneof"`
}

type OutboundContent_Interactive struct {
	Interactive *InteractiveMessage `protobuf:"bytes,4,opt,name=interactive,proto3,oneof"`
}

func (*OutboundContent_Text) isOutboundContent_Value() {}

func (*OutboundContent_Template) isOutboundContent_Value() {}

func (*OutboundContent_Media) isOutboundContent_Value() {}

func (*OutboundContent_Interactive) isOutboundContent_Value() {}

type TemplateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Components    []*TemplateComponent   `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateMessage) Reset() {
	*x = TemplateMessage{}
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateMessage) ProtoMessage() {}

func (x *TemplateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateMessage.ProtoReflect.Descriptor instead.
func (*TemplateMessage) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{10}
}

func (x *TemplateMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateMessage) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TemplateMessage) GetComponents() []*TemplateComponent {
	if x != nil {
		return x.Components
	}
	return nil
}

type TemplateComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // header, body, button
	Parameters    []*TemplateParameter   `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateComponent) Reset() {
	*x = TemplateComponent{}
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateComponent) ProtoMessage() {}

func (x *TemplateComponent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateComponent.ProtoReflect.Descriptor instead.
func (*TemplateComponent) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{11}
}

func (x *TemplateComponent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TemplateComponent) GetParameters() []*TemplateParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type TemplateParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // text, image, document, video
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateParameter) Reset() {
	*x = TemplateParameter{}
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateParameter) ProtoMessage() {}

func (x *TemplateParameter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateParameter.ProtoReflect.Descriptor instead.
func (*TemplateParameter) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{12}
}

func (x *TemplateParameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TemplateParameter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type InteractiveMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // button, list
	Body          *InteractiveBody       `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Buttons       []*InteractiveButton   `protobuf:"bytes,3,rep,name=buttons,proto3" json:"buttons,omitempty"`
	Sections      []*InteractiveSection  `protobuf:"bytes,4,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractiveMessage) Reset() {
	*x = InteractiveMessage{}
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractiveMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractiveMessage) ProtoMessage() {}

func (x *InteractiveMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractiveMessage.ProtoReflect.Descriptor instead.
func (*InteractiveMessage) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{13}
}

func (x *InteractiveMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InteractiveMessage) GetBody() *InteractiveBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *InteractiveMessage) GetButtons() []*InteractiveButton {
	if x != nil {
		return x.Buttons
	}
	return nil
}

func (x *InteractiveMessage) GetSections() []*InteractiveSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

type InteractiveBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractiveBody) Reset() {
	*x = InteractiveBody{}
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractiveBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractiveBody) ProtoMessage() {}

func (x *InteractiveBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractiveBody.ProtoReflect.Descriptor instead.
func (*InteractiveBody) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{14}
}

func (x *InteractiveBody) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type InteractiveButton struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractiveButton) Reset() {
	*x = InteractiveButton{}
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractiveButton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractiveButton) ProtoMessage() {}

func (x *InteractiveButton) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractiveButton.ProtoReflect.Descriptor instead.
func (*InteractiveButton) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{15}
}

func (x *InteractiveButton) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InteractiveButton) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type InteractiveSection struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Title         string                   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Rows          []*InteractiveSectionRow `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractiveSection) Reset() {
	*x = InteractiveSection{}
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractiveSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractiveSection) ProtoMessage() {}

func (x *InteractiveSection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractiveSection.ProtoReflect.Descriptor instead.
func (*InteractiveSection) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{16}
}

func (x *InteractiveSection) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InteractiveSection) GetRows() []*InteractiveSectionRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type InteractiveSectionRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractiveSectionRow) Reset() {
	*x = InteractiveSectionRow{}
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractiveSectionRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractiveSectionRow) ProtoMessage() {}

func (x *InteractiveSectionRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractiveSectionRow.ProtoReflect.Descriptor instead.
func (*InteractiveSectionRow) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{17}
}

func (x *InteractiveSectionRow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InteractiveSectionRow) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InteractiveSectionRow) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type StatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	WabaId        string                 `protobuf:"bytes,2,opt,name=waba_id,json=wabaId,proto3" json:"waba_id,omitempty"`
	Status        MessageStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=whatsapp.MessageStatus" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RecipientId   string                 `protobuf:"bytes,5,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_whatsapp_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_whatsapp_proto_rawDescGZIP(), []int{18}
}

func (x *StatusUpdate) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *StatusUpdate) GetWabaId() string {
	if x != nil {
		return x.WabaId
	}
	return ""
}

func (x *StatusUpdate) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_STATUS_UNKNOWN
}

func (x *StatusUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StatusUpdate) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

var File_proto_whatsapp_whatsapp_proto protoreflect.FileDescriptor

const file_proto_whatsapp_whatsapp_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/whatsapp/whatsapp.proto\x12\bwhatsapp\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x02\n" +
	"\x0eInboundMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\awaba_id\x18\x02 \x01(\tR\x06wabaId\x12&\n" +
	"\x0fphone_number_id\x18\x03 \x01(\tR\rphoneNumberId\x12\x12\n" +
	"\x04from\x18\x04 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x05 \x01(\tR\x02to\x12)\n" +
	"\x04type\x18\x06 \x01(\x0e2\x15.whatsapp.MessageTypeR\x04type\x122\n" +
	"\acontent\x18\a \x01(\v2\x18.whatsapp.MessageContentR\acontent\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12+\n" +
	"\acontact\x18\t \x01(\v2\x11.whatsapp.ContactR\acontact\"\xa0\x02\n" +
	"\x0eMessageContent\x12+\n" +
	"\x04text\x18\x01 \x01(\v2\x15.whatsapp.TextMessageH\x00R\x04text\x12.\n" +
	"\x05media\x18\x02 \x01(\v2\x16.whatsapp.MediaMessageH\x00R\x05media\x127\n" +
	"\blocation\x18\x03 \x01(\v2\x19.whatsapp.LocationMessageH\x00R\blocation\x12>\n" +
	"\vinteractive\x18\x04 \x01(\v2\x1a.whatsapp.InteractiveReplyH\x00R\vinteractive\x12/\n" +
	"\x06button\x18\x05 \x01(\v2\x15.whatsapp.ButtonReplyH\x00R\x06buttonB\a\n" +
	"\x05value\"!\n" +
	"\vTextMessage\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\"\x94\x01\n" +
	"\fMediaMessage\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x18\n" +
	"\acaption\x18\x04 \x01(\tR\acaption\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\"y\n" +
	"\x0fLocationMessage\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\"Z\n" +
	"\x10InteractiveReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"3\n" +
	"\vButtonReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"2\n" +
	"\aContact\x12\x13\n" +
	"\x05wa_id\x18\x01 \x01(\tR\x04waId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xc0\x01\n" +
	"\x0fOutboundMessage\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12&\n" +
	"\x0fphone_number_id\x18\x02 \x01(\tR\rphoneNumberId\x12\x17\n" +
	"\awaba_id\x18\x03 \x01(\tR\x06wabaId\x123\n" +
	"\acontent\x18\x04 \x01(\v2\x19.whatsapp.OutboundContentR\acontent\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"\xf2\x01\n" +
	"\x0fOutboundContent\x12+\n" +
	"\x04text\x18\x01 \x01(\v2\x15.whatsapp.TextMessageH\x00R\x04text\x127\n" +
	"\btemplate\x18\x02 \x01(\v2\x19.whatsapp.TemplateMessageH\x00R\btemplate\x12.\n" +
	"\x05media\x18\x03 \x01(\v2\x16.whatsapp.MediaMessageH\x00R\x05media\x12@\n" +
	"\vinteractive\x18\x04 \x01(\v2\x1c.whatsapp.InteractiveMessageH\x00R\vinteractiveB\a\n" +
	"\x05value\"~\n" +
	"\x0fTemplateMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12;\n" +
	"\n" +
	"components\x18\x03 \x03(\v2\x1b.whatsapp.TemplateComponentR\n" +
	"components\"d\n" +
	"\x11TemplateComponent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12;\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2\x1b.whatsapp.TemplateParameterR\n" +
	"parameters\"=\n" +
	"\x11TemplateParameter\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xc8\x01\n" +
	"\x12InteractiveMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12-\n" +
	"\x04body\x18\x02 \x01(\v2\x19.whatsapp.InteractiveBodyR\x04body\x125\n" +
	"\abuttons\x18\x03 \x03(\v2\x1b.whatsapp.InteractiveButtonR\abuttons\x128\n" +
	"\bsections\x18\x04 \x03(\v2\x1c.whatsapp.InteractiveSectionR\bsections\"%\n" +
	"\x0fInteractiveBody\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"9\n" +
	"\x11InteractiveButton\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"_\n" +
	"\x12InteractiveSection\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x123\n" +
	"\x04rows\x18\x02 \x03(\v2\x1f.whatsapp.InteractiveSectionRowR\x04rows\"_\n" +
	"\x15InteractiveSectionRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xd4\x01\n" +
	"\fStatusUpdate\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\awaba_id\x18\x02 \x01(\tR\x06wabaId\x12/\n" +
	"\x06status\x18\x03 \x01(\x0e2\x17.whatsapp.MessageStatusR\x06status\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\frecipient_id\x18\x05 \x01(\tR\vrecipientId*n\n" +
	"\rMessageStatus\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vSTATUS_SENT\x10\x01\x12\x14\n" +
	"\x10STATUS_DELIVERED\x10\x02\x12\x0f\n" +
	"\vSTATUS_READ\x10\x03\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x04*\xd0\x01\n" +
	"\vMessageType\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\r\n" +
	"\tTYPE_TEXT\x10\x01\x12\x0e\n" +
	"\n" +
	"TYPE_IMAGE\x10\x02\x12\x0e\n" +
	"\n" +
	"TYPE_VIDEO\x10\x03\x12\x0e\n" +
	"\n" +
	"TYPE_AUDIO\x10\x04\x12\x11\n" +
	"\rTYPE_DOCUMENT\x10\x05\x12\x11\n" +
	"\rTYPE_LOCATION\x10\x06\x12\x11\n" +
	"\rTYPE_CONTACTS\x10\a\x12\x14\n" +
	"\x10TYPE_INTERACTIVE\x10\b\x12\x0f\n" +
	"\vTYPE_BUTTON\x10\t\x12\x10\n" +
	"\fTYPE_STICKER\x10\n" +
	"B\"Z github.com/usegro/proto/whatsappb\x06proto3"

var (
	file_proto_whatsapp_whatsapp_proto_rawDescOnce sync.Once
	file_proto_whatsapp_whatsapp_proto_rawDescData []byte
)

func file_proto_whatsapp_whatsapp_proto_rawDescGZIP() []byte {
	file_proto_whatsapp_whatsapp_proto_rawDescOnce.Do(func() {
		file_proto_whatsapp_whatsapp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_whatsapp_whatsapp_proto_rawDesc), len(file_proto_whatsapp_whatsapp_proto_rawDesc)))
	})
	return file_proto_whatsapp_whatsapp_proto_rawDescData
}

var file_proto_whatsapp_whatsapp_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_whatsapp_whatsapp_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_whatsapp_whatsapp_proto_goTypes = []any{
	(MessageStatus)(0),            // 0: whatsapp.MessageStatus
	(MessageType)(0),              // 1: whatsapp.MessageType
	(*InboundMessage)(nil),        // 2: whatsapp.InboundMessage
	(*MessageContent)(nil),        // 3: whatsapp.MessageContent
	(*TextMessage)(nil),           // 4: whatsapp.TextMessage
	(*MediaMessage)(nil),          // 5: whatsapp.MediaMessage
	(*LocationMessage)(nil),       // 6: whatsapp.LocationMessage
	(*InteractiveReply)(nil),      // 7: whatsapp.InteractiveReply
	(*ButtonReply)(nil),           // 8: whatsapp.ButtonReply
	(*Contact)(nil),               // 9: whatsapp.Contact
	(*OutboundMessage)(nil),       // 10: whatsapp.OutboundMessage
	(*OutboundContent)(nil),       // 11: whatsapp.OutboundContent
	(*TemplateMessage)(nil),       // 12: whatsapp.TemplateMessage
	(*TemplateComponent)(nil),     // 13: whatsapp.TemplateComponent
	(*TemplateParameter)(nil),     // 14: whatsapp.TemplateParameter
	(*InteractiveMessage)(nil),    // 15: whatsapp.InteractiveMessage
	(*InteractiveBody)(nil),       // 16: whatsapp.InteractiveBody
	(*InteractiveButton)(nil),     // 17: whatsapp.InteractiveButton
	(*InteractiveSection)(nil),    // 18: whatsapp.InteractiveSection
	(*InteractiveSectionRow)(nil), // 19: whatsapp.InteractiveSectionRow
	(*StatusUpdate)(nil),          // 20: whatsapp.StatusUpdate
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_proto_whatsapp_whatsapp_proto_depIdxs = []int32{
	1,  // 0: whatsapp.InboundMessage.type:type_name -> whatsapp.MessageType
	3,  // 1: whatsapp.InboundMessage.content:type_name -> whatsapp.MessageContent
	21, // 2: whatsapp.InboundMessage.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 3: whatsapp.InboundMessage.contact:type_name -> whatsapp.Contact
	4,  // 4: whatsapp.MessageContent.text:type_name -> whatsapp.TextMessage
	5,  // 5: whatsapp.MessageContent.media:type_name -> whatsapp.MediaMessage
	6,  // 6: whatsapp.MessageContent.location:type_name -> whatsapp.LocationMessage
	7,  // 7: whatsapp.MessageContent.interactive:type_name -> whatsapp.InteractiveReply
	8,  // 8: whatsapp.MessageContent.button:type_name -> whatsapp.ButtonReply
	11, // 9: whatsapp.OutboundMessage.content:type_name -> whatsapp.OutboundContent
	4,  // 10: whatsapp.OutboundContent.text:type_name -> whatsapp.TextMessage
	12, // 11: whatsapp.OutboundContent.template:type_name -> whatsapp.TemplateMessage
	5,  // 12: whatsapp.OutboundContent.media:type_name -> whatsapp.MediaMessage
	15, // 13: whatsapp.OutboundContent.interactive:type_name -> whatsapp.InteractiveMessage
	13, // 14: whatsapp.TemplateMessage.components:type_name -> whatsapp.TemplateComponent
	14, // 15: whatsapp.TemplateComponent.parameters:type_name -> whatsapp.TemplateParameter
	16, // 16: whatsapp.InteractiveMessage.body:type_name -> whatsapp.InteractiveBody
	17, // 17: whatsapp.InteractiveMessage.buttons:type_name -> whatsapp.InteractiveButton
	18, // 18: whatsapp.InteractiveMessage.sections:type_name -> whatsapp.InteractiveSection
	19, // 19: whatsapp.InteractiveSection.rows:type_name -> whatsapp.InteractiveSectionRow
	0,  // 20: whatsapp.StatusUpdate.status:type_name -> whatsapp.MessageStatus
	21, // 21: whatsapp.StatusUpdate.timestamp:type_name -> google.protobuf.Timestamp
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_whatsapp_whatsapp_proto_init() }
func file_proto_whatsapp_whatsapp_proto_init() {
	if File_proto_whatsapp_whatsapp_proto != nil {
		return
	}
	file_proto_whatsapp_whatsapp_proto_msgTypes[1].OneofWrappers = []any{
		(*MessageContent_Text)(nil),
		(*MessageContent_Media)(nil),
		(*MessageContent_Location)(nil),
		(*MessageContent_Interactive)(nil),
		(*MessageContent_Button)(nil),
	}
	file_proto_whatsapp_whatsapp_proto_msgTypes[9].OneofWrappers = []any{
		(*OutboundContent_Text)(nil),
		(*OutboundContent_Template)(nil),
		(*OutboundContent_Media)(nil),
		(*OutboundContent_Interactive)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_whatsapp_whatsapp_proto_rawDesc), len(file_proto_whatsapp_whatsapp_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_whatsapp_whatsapp_proto_goTypes,
		DependencyIndexes: file_proto_whatsapp_whatsapp_proto_depIdxs,
		EnumInfos:         file_proto_whatsapp_whatsapp_proto_enumTypes,
		MessageInfos:      file_proto_whatsapp_whatsapp_proto_msgTypes,
	}.Build()
	File_proto_whatsapp_whatsapp_proto = out.File
	file_proto_whatsapp_whatsapp_proto_goTypes = nil
	file_proto_whatsapp_whatsapp_proto_depIdxs = nil
}
