// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/crm/crm.proto

package crm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TenantStatus int32

const (
	TenantStatus_TENANT_PENDING   TenantStatus = 0
	TenantStatus_TENANT_ACTIVE    TenantStatus = 1
	TenantStatus_TENANT_SUSPENDED TenantStatus = 2
)

// Enum value maps for TenantStatus.
var (
	TenantStatus_name = map[int32]string{
		0: "TENANT_PENDING",
		1: "TENANT_ACTIVE",
		2: "TENANT_SUSPENDED",
	}
	TenantStatus_value = map[string]int32{
		"TENANT_PENDING":   0,
		"TENANT_ACTIVE":    1,
		"TENANT_SUSPENDED": 2,
	}
)

func (x TenantStatus) Enum() *TenantStatus {
	p := new(TenantStatus)
	*p = x
	return p
}

func (x TenantStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TenantStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_crm_crm_proto_enumTypes[0].Descriptor()
}

func (TenantStatus) Type() protoreflect.EnumType {
	return &file_proto_crm_crm_proto_enumTypes[0]
}

func (x TenantStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TenantStatus.Descriptor instead.
func (TenantStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{0}
}

type LifecycleStage int32

const (
	LifecycleStage_STAGE_UNKNOWN  LifecycleStage = 0
	LifecycleStage_STAGE_LEAD     LifecycleStage = 1
	LifecycleStage_STAGE_MQL      LifecycleStage = 2
	LifecycleStage_STAGE_SQL      LifecycleStage = 3
	LifecycleStage_STAGE_CUSTOMER LifecycleStage = 4
	LifecycleStage_STAGE_CHURNED  LifecycleStage = 5
)

// Enum value maps for LifecycleStage.
var (
	LifecycleStage_name = map[int32]string{
		0: "STAGE_UNKNOWN",
		1: "STAGE_LEAD",
		2: "STAGE_MQL",
		3: "STAGE_SQL",
		4: "STAGE_CUSTOMER",
		5: "STAGE_CHURNED",
	}
	LifecycleStage_value = map[string]int32{
		"STAGE_UNKNOWN":  0,
		"STAGE_LEAD":     1,
		"STAGE_MQL":      2,
		"STAGE_SQL":      3,
		"STAGE_CUSTOMER": 4,
		"STAGE_CHURNED":  5,
	}
)

func (x LifecycleStage) Enum() *LifecycleStage {
	p := new(LifecycleStage)
	*p = x
	return p
}

func (x LifecycleStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LifecycleStage) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_crm_crm_proto_enumTypes[1].Descriptor()
}

func (LifecycleStage) Type() protoreflect.EnumType {
	return &file_proto_crm_crm_proto_enumTypes[1]
}

func (x LifecycleStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LifecycleStage.Descriptor instead.
func (LifecycleStage) EnumDescriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{1}
}

type LeadStatus int32

const (
	LeadStatus_LEAD_OPEN LeadStatus = 0
	LeadStatus_LEAD_WON  LeadStatus = 1
	LeadStatus_LEAD_LOST LeadStatus = 2
)

// Enum value maps for LeadStatus.
var (
	LeadStatus_name = map[int32]string{
		0: "LEAD_OPEN",
		1: "LEAD_WON",
		2: "LEAD_LOST",
	}
	LeadStatus_value = map[string]int32{
		"LEAD_OPEN": 0,
		"LEAD_WON":  1,
		"LEAD_LOST": 2,
	}
)

func (x LeadStatus) Enum() *LeadStatus {
	p := new(LeadStatus)
	*p = x
	return p
}

func (x LeadStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeadStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_crm_crm_proto_enumTypes[2].Descriptor()
}

func (LeadStatus) Type() protoreflect.EnumType {
	return &file_proto_crm_crm_proto_enumTypes[2]
}

func (x LeadStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeadStatus.Descriptor instead.
func (LeadStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{2}
}

type UserRole int32

const (
	UserRole_ROLE_AGENT UserRole = 0
	UserRole_ROLE_ADMIN UserRole = 1
	UserRole_ROLE_OWNER UserRole = 2
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "ROLE_AGENT",
		1: "ROLE_ADMIN",
		2: "ROLE_OWNER",
	}
	UserRole_value = map[string]int32{
		"ROLE_AGENT": 0,
		"ROLE_ADMIN": 1,
		"ROLE_OWNER": 2,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_crm_crm_proto_enumTypes[3].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_proto_crm_crm_proto_enumTypes[3]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{3}
}

type Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	WabaId        string                 `protobuf:"bytes,3,opt,name=waba_id,json=wabaId,proto3" json:"waba_id,omitempty"`
	PhoneNumberId string                 `protobuf:"bytes,4,opt,name=phone_number_id,json=phoneNumberId,proto3" json:"phone_number_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,5,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // encrypted at rest
	Status        TenantStatus           `protobuf:"varint,6,opt,name=status,proto3,enum=crm.TenantStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_proto_crm_crm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{0}
}

func (x *Tenant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetWabaId() string {
	if x != nil {
		return x.WabaId
	}
	return ""
}

func (x *Tenant) GetPhoneNumberId() string {
	if x != nil {
		return x.PhoneNumberId
	}
	return ""
}

func (x *Tenant) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Tenant) GetStatus() TenantStatus {
	if x != nil {
		return x.Status
	}
	return TenantStatus_TENANT_PENDING
}

func (x *Tenant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	WabaId        string                 `protobuf:"bytes,2,opt,name=waba_id,json=wabaId,proto3" json:"waba_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_proto_crm_crm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTenantRequest) GetWabaId() string {
	if x != nil {
		return x.WabaId
	}
	return ""
}

func (x *CreateTenantRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type GetTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantRequest) Reset() {
	*x = GetTenantRequest{}
	mi := &file_proto_crm_crm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantRequest) ProtoMessage() {}

func (x *GetTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantRequest.ProtoReflect.Descriptor instead.
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{2}
}

func (x *GetTenantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumberId string                 `protobuf:"bytes,3,opt,name=phone_number_id,json=phoneNumberId,proto3" json:"phone_number_id,omitempty"`
	Status        TenantStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=crm.TenantStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantRequest) Reset() {
	*x = UpdateTenantRequest{}
	mi := &file_proto_crm_crm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantRequest) ProtoMessage() {}

func (x *UpdateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantRequest) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTenantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTenantRequest) GetPhoneNumberId() string {
	if x != nil {
		return x.PhoneNumberId
	}
	return ""
}

func (x *UpdateTenantRequest) GetStatus() TenantStatus {
	if x != nil {
		return x.Status
	}
	return TenantStatus_TENANT_PENDING
}

type Contact struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Phone          string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Email          string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	OptedIn        bool                   `protobuf:"varint,6,opt,name=opted_in,json=optedIn,proto3" json:"opted_in,omitempty"`
	LifecycleStage LifecycleStage         `protobuf:"varint,7,opt,name=lifecycle_stage,json=lifecycleStage,proto3,enum=crm.LifecycleStage" json:"lifecycle_stage,omitempty"`
	CustomFields   map[string]string      `protobuf:"bytes,8,rep,name=custom_fields,json=customFields,proto3" json:"custom_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags           []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastSeenAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_proto_crm_crm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{4}
}

func (x *Contact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Contact) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Contact) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Contact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Contact) GetOptedIn() bool {
	if x != nil {
		return x.OptedIn
	}
	return false
}

func (x *Contact) GetLifecycleStage() LifecycleStage {
	if x != nil {
		return x.LifecycleStage
	}
	return LifecycleStage_STAGE_UNKNOWN
}

func (x *Contact) GetCustomFields() map[string]string {
	if x != nil {
		return x.CustomFields
	}
	return nil
}

func (x *Contact) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Contact) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Contact) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

type CreateContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContactRequest) Reset() {
	*x = CreateContactRequest{}
	mi := &file_proto_crm_crm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContactRequest) ProtoMessage() {}

func (x *CreateContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContactRequest.ProtoReflect.Descriptor instead.
func (*CreateContactRequest) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{5}
}

func (x *CreateContactRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateContactRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateContactRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateContactRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactRequest) Reset() {
	*x = GetContactRequest{}
	mi := &file_proto_crm_crm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactRequest) ProtoMessage() {}

func (x *GetContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactRequest.ProtoReflect.Descriptor instead.
func (*GetContactRequest) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{6}
}

func (x *GetContactRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetContactRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type UpdateContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contact       *Contact               `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContactRequest) Reset() {
	*x = UpdateContactRequest{}
	mi := &file_proto_crm_crm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContactRequest) ProtoMessage() {}

func (x *UpdateContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContactRequest.ProtoReflect.Descriptor instead.
func (*UpdateContactRequest) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateContactRequest) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

type UpsertContactByPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertContactByPhoneRequest) Reset() {
	*x = UpsertContactByPhoneRequest{}
	mi := &file_proto_crm_crm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertContactByPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertContactByPhoneRequest) ProtoMessage() {}

func (x *UpsertContactByPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertContactByPhoneRequest.ProtoReflect.Descriptor instead.
func (*UpsertContactByPhoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{8}
}

func (x *UpsertContactByPhoneRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpsertContactByPhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpsertContactByPhoneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListContactsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Page           int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search         string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	Tags           []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	LifecycleStage LifecycleStage         `protobuf:"varint,6,opt,name=lifecycle_stage,json=lifecycleStage,proto3,enum=crm.LifecycleStage" json:"lifecycle_stage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListContactsRequest) Reset() {
	*x = ListContactsRequest{}
	mi := &file_proto_crm_crm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContactsRequest) ProtoMessage() {}

func (x *ListContactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContactsRequest.ProtoReflect.Descriptor instead.
func (*ListContactsRequest) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{9}
}

func (x *ListContactsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListContactsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListContactsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListContactsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListContactsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListContactsRequest) GetLifecycleStage() LifecycleStage {
	if x != nil {
		return x.LifecycleStage
	}
	return LifecycleStage_STAGE_UNKNOWN
}

type ListContactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contacts      []*Contact             `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContactsResponse) Reset() {
	*x = ListContactsResponse{}
	mi := &file_proto_crm_crm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContactsResponse) ProtoMessage() {}

func (x *ListContactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContactsResponse.ProtoReflect.Descriptor instead.
func (*ListContactsResponse) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{10}
}

func (x *ListContactsResponse) GetContacts() []*Contact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *ListContactsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Lead struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ContactId      string                 `protobuf:"bytes,3,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Value          float64                `protobuf:"fixed64,5,opt,name=value,proto3" json:"value,omitempty"`
	Status         LeadStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=crm.LeadStatus" json:"status,omitempty"`
	LifecycleStage LifecycleStage         `protobuf:"varint,7,opt,name=lifecycle_stage,json=lifecycleStage,proto3,enum=crm.LifecycleStage" json:"lifecycle_stage,omitempty"`
	AssignedTo     string                 `protobuf:"bytes,8,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Lead) Reset() {
	*x = Lead{}
	mi := &file_proto_crm_crm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lead) ProtoMessage() {}

func (x *Lead) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lead.ProtoReflect.Descriptor instead.
func (*Lead) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{11}
}

func (x *Lead) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lead) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Lead) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *Lead) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Lead) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Lead) GetStatus() LeadStatus {
	if x != nil {
		return x.Status
	}
	return LeadStatus_LEAD_OPEN
}

func (x *Lead) GetLifecycleStage() LifecycleStage {
	if x != nil {
		return x.LifecycleStage
	}
	return LifecycleStage_STAGE_UNKNOWN
}

func (x *Lead) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *Lead) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ContactId     string                 `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLeadRequest) Reset() {
	*x = CreateLeadRequest{}
	mi := &file_proto_crm_crm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeadRequest) ProtoMessage() {}

func (x *CreateLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeadRequest.ProtoReflect.Descriptor instead.
func (*CreateLeadRequest) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{12}
}

func (x *CreateLeadRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateLeadRequest) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *CreateLeadRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLeadRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UpdateLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lead          *Lead                  `protobuf:"bytes,1,opt,name=lead,proto3" json:"lead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLeadRequest) Reset() {
	*x = UpdateLeadRequest{}
	mi := &file_proto_crm_crm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLeadRequest) ProtoMessage() {}

func (x *UpdateLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLeadRequest.ProtoReflect.Descriptor instead.
func (*UpdateLeadRequest) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateLeadRequest) GetLead() *Lead {
	if x != nil {
		return x.Lead
	}
	return nil
}

type ListLeadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeadsRequest) Reset() {
	*x = ListLeadsRequest{}
	mi := &file_proto_crm_crm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeadsRequest) ProtoMessage() {}

func (x *ListLeadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeadsRequest.ProtoReflect.Descriptor instead.
func (*ListLeadsRequest) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{14}
}

func (x *ListLeadsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListLeadsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLeadsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListLeadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leads         []*Lead                `protobuf:"bytes,1,rep,name=leads,proto3" json:"leads,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeadsResponse) Reset() {
	*x = ListLeadsResponse{}
	mi := &file_proto_crm_crm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeadsResponse) ProtoMessage() {}

func (x *ListLeadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeadsResponse.ProtoReflect.Descriptor instead.
func (*ListLeadsResponse) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{15}
}

func (x *ListLeadsResponse) GetLeads() []*Lead {
	if x != nil {
		return x.Leads
	}
	return nil
}

func (x *ListLeadsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateLifecycleStageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeadId        string                 `protobuf:"bytes,1,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	Stage         LifecycleStage         `protobuf:"varint,2,opt,name=stage,proto3,enum=crm.LifecycleStage" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLifecycleStageRequest) Reset() {
	*x = UpdateLifecycleStageRequest{}
	mi := &file_proto_crm_crm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLifecycleStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLifecycleStageRequest) ProtoMessage() {}

func (x *UpdateLifecycleStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLifecycleStageRequest.ProtoReflect.Descriptor instead.
func (*UpdateLifecycleStageRequest) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateLifecycleStageRequest) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

func (x *UpdateLifecycleStageRequest) GetStage() LifecycleStage {
	if x != nil {
		return x.Stage
	}
	return LifecycleStage_STAGE_UNKNOWN
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Role          UserRole               `protobuf:"varint,5,opt,name=role,proto3,enum=crm.UserRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_crm_crm_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{17}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_ROLE_AGENT
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Role          UserRole               `protobuf:"varint,5,opt,name=role,proto3,enum=crm.UserRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_crm_crm_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{18}
}

func (x *CreateUserRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_ROLE_AGENT
}

type AuthenticateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateUserRequest) Reset() {
	*x = AuthenticateUserRequest{}
	mi := &file_proto_crm_crm_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateUserRequest) ProtoMessage() {}

func (x *AuthenticateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateUserRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{19}
}

func (x *AuthenticateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthenticateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_crm_crm_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{20}
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_proto_crm_crm_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{21}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_proto_crm_crm_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{22}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type CrmOrganization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	BusinessName  string                 `protobuf:"bytes,4,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	BusinessInfo  string                 `protobuf:"bytes,5,opt,name=business_info,json=businessInfo,proto3" json:"business_info,omitempty"`
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrmOrganization) Reset() {
	*x = CrmOrganization{}
	mi := &file_proto_crm_crm_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrmOrganization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrmOrganization) ProtoMessage() {}

func (x *CrmOrganization) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrmOrganization.ProtoReflect.Descriptor instead.
func (*CrmOrganization) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{23}
}

func (x *CrmOrganization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CrmOrganization) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CrmOrganization) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CrmOrganization) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

func (x *CrmOrganization) GetBusinessInfo() string {
	if x != nil {
		return x.BusinessInfo
	}
	return ""
}

func (x *CrmOrganization) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *CrmOrganization) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListOrganizationsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsByUserRequest) Reset() {
	*x = ListOrganizationsByUserRequest{}
	mi := &file_proto_crm_crm_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsByUserRequest) ProtoMessage() {}

func (x *ListOrganizationsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsByUserRequest.ProtoReflect.Descriptor instead.
func (*ListOrganizationsByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{24}
}

func (x *ListOrganizationsByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListOrganizationsByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizations []*CrmOrganization     `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsByUserResponse) Reset() {
	*x = ListOrganizationsByUserResponse{}
	mi := &file_proto_crm_crm_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsByUserResponse) ProtoMessage() {}

func (x *ListOrganizationsByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crm_crm_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsByUserResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationsByUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_crm_crm_proto_rawDescGZIP(), []int{25}
}

func (x *ListOrganizationsByUserResponse) GetOrganizations() []*CrmOrganization {
	if x != nil {
		return x.Organizations
	}
	return nil
}

var File_proto_crm_crm_proto protoreflect.FileDescriptor

const file_proto_crm_crm_proto_rawDesc = "" +
	"\n" +
	"\x13proto/crm/crm.proto\x12\x03crm\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\x01\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\awaba_id\x18\x03 \x01(\tR\x06wabaId\x12&\n" +
	"\x0fphone_number_id\x18\x04 \x01(\tR\rphoneNumberId\x12!\n" +
	"\faccess_token\x18\x05 \x01(\tR\vaccessToken\x12)\n" +
	"\x06status\x18\x06 \x01(\x0e2\x11.crm.TenantStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"e\n" +
	"\x13CreateTenantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\awaba_id\x18\x02 \x01(\tR\x06wabaId\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\"\"\n" +
	"\x10GetTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8c\x01\n" +
	"\x13UpdateTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0fphone_number_id\x18\x03 \x01(\tR\rphoneNumberId\x12)\n" +
	"\x06status\x18\x04 \x01(\x0e2\x11.crm.TenantStatusR\x06status\"\xe2\x03\n" +
	"\aContact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x19\n" +
	"\bopted_in\x18\x06 \x01(\bR\aoptedIn\x12<\n" +
	"\x0flifecycle_stage\x18\a \x01(\x0e2\x13.crm.LifecycleStageR\x0elifecycleStage\x12C\n" +
	"\rcustom_fields\x18\b \x03(\v2\x1e.crm.Contact.CustomFieldsEntryR\fcustomFields\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_seen_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x1a?\n" +
	"\x11CustomFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\x14CreateContactRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"@\n" +
	"\x11GetContactRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\">\n" +
	"\x14UpdateContactRequest\x12&\n" +
	"\acontact\x18\x01 \x01(\v2\f.crm.ContactR\acontact\"d\n" +
	"\x1bUpsertContactByPhoneRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xcd\x01\n" +
	"\x13ListContactsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12<\n" +
	"\x0flifecycle_stage\x18\x06 \x01(\x0e2\x13.crm.LifecycleStageR\x0elifecycleStage\"V\n" +
	"\x14ListContactsResponse\x12(\n" +
	"\bcontacts\x18\x01 \x03(\v2\f.crm.ContactR\bcontacts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xc1\x02\n" +
	"\x04Lead\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x03 \x01(\tR\tcontactId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x01R\x05value\x12'\n" +
	"\x06status\x18\x06 \x01(\x0e2\x0f.crm.LeadStatusR\x06status\x12<\n" +
	"\x0flifecycle_stage\x18\a \x01(\x0e2\x13.crm.LifecycleStageR\x0elifecycleStage\x12\x1f\n" +
	"\vassigned_to\x18\b \x01(\tR\n" +
	"assignedTo\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"{\n" +
	"\x11CreateLeadRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x02 \x01(\tR\tcontactId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\"2\n" +
	"\x11UpdateLeadRequest\x12\x1d\n" +
	"\x04lead\x18\x01 \x01(\v2\t.crm.LeadR\x04lead\"`\n" +
	"\x10ListLeadsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"J\n" +
	"\x11ListLeadsResponse\x12\x1f\n" +
	"\x05leads\x18\x01 \x03(\v2\t.crm.LeadR\x05leads\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"a\n" +
	"\x1bUpdateLifecycleStageRequest\x12\x17\n" +
	"\alead_id\x18\x01 \x01(\tR\x06leadId\x12)\n" +
	"\x05stage\x18\x02 \x01(\x0e2\x13.crm.LifecycleStageR\x05stage\"\x80\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12!\n" +
	"\x04role\x18\x05 \x01(\x0e2\r.crm.UserRoleR\x04role\"\x99\x01\n" +
	"\x11CreateUserRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12!\n" +
	"\x04role\x18\x05 \x01(\x0e2\r.crm.UserRoleR\x04role\"K\n" +
	"\x17AuthenticateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"C\n" +
	"\fAuthResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\x04user\x18\x02 \x01(\v2\t.crm.UserR\x04user\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"L\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1d\n" +
	"\x04user\x18\x02 \x01(\v2\t.crm.UserR\x04user\"\xf4\x01\n" +
	"\x0fCrmOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12#\n" +
	"\rbusiness_name\x18\x04 \x01(\tR\fbusinessName\x12#\n" +
	"\rbusiness_info\x18\x05 \x01(\tR\fbusinessInfo\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"9\n" +
	"\x1eListOrganizationsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"]\n" +
	"\x1fListOrganizationsByUserResponse\x12:\n" +
	"\rorganizations\x18\x01 \x03(\v2\x14.crm.CrmOrganizationR\rorganizations*K\n" +
	"\fTenantStatus\x12\x12\n" +
	"\x0eTENANT_PENDING\x10\x00\x12\x11\n" +
	"\rTENANT_ACTIVE\x10\x01\x12\x14\n" +
	"\x10TENANT_SUSPENDED\x10\x02*x\n" +
	"\x0eLifecycleStage\x12\x11\n" +
	"\rSTAGE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"STAGE_LEAD\x10\x01\x12\r\n" +
	"\tSTAGE_MQL\x10\x02\x12\r\n" +
	"\tSTAGE_SQL\x10\x03\x12\x12\n" +
	"\x0eSTAGE_CUSTOMER\x10\x04\x12\x11\n" +
	"\rSTAGE_CHURNED\x10\x05*8\n" +
	"\n" +
	"LeadStatus\x12\r\n" +
	"\tLEAD_OPEN\x10\x00\x12\f\n" +
	"\bLEAD_WON\x10\x01\x12\r\n" +
	"\tLEAD_LOST\x10\x02*:\n" +
	"\bUserRole\x12\x0e\n" +
	"\n" +
	"ROLE_AGENT\x10\x00\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x01\x12\x0e\n" +
	"\n" +
	"ROLE_OWNER\x10\x022\xe7\a\n" +
	"\n" +
	"CRMService\x125\n" +
	"\fCreateTenant\x12\x18.crm.CreateTenantRequest\x1a\v.crm.Tenant\x12/\n" +
	"\tGetTenant\x12\x15.crm.GetTenantRequest\x1a\v.crm.Tenant\x125\n" +
	"\fUpdateTenant\x12\x18.crm.UpdateTenantRequest\x1a\v.crm.Tenant\x128\n" +
	"\rCreateContact\x12\x19.crm.CreateContactRequest\x1a\f.crm.Contact\x122\n" +
	"\n" +
	"GetContact\x12\x16.crm.GetContactRequest\x1a\f.crm.Contact\x128\n" +
	"\rUpdateContact\x12\x19.crm.UpdateContactRequest\x1a\f.crm.Contact\x12C\n" +
	"\fListContacts\x12\x18.crm.ListContactsRequest\x1a\x19.crm.ListContactsResponse\x12F\n" +
	"\x14UpsertContactByPhone\x12 .crm.UpsertContactByPhoneRequest\x1a\f.crm.Contact\x12/\n" +
	"\n" +
	"CreateLead\x12\x16.crm.CreateLeadRequest\x1a\t.crm.Lead\x12/\n" +
	"\n" +
	"UpdateLead\x12\x16.crm.UpdateLeadRequest\x1a\t.crm.Lead\x12:\n" +
	"\tListLeads\x12\x15.crm.ListLeadsRequest\x1a\x16.crm.ListLeadsResponse\x12C\n" +
	"\x14UpdateLifecycleStage\x12 .crm.UpdateLifecycleStageRequest\x1a\t.crm.Lead\x12/\n" +
	"\n" +
	"CreateUser\x12\x16.crm.CreateUserRequest\x1a\t.crm.User\x12C\n" +
	"\x10AuthenticateUser\x12\x1c.crm.AuthenticateUserRequest\x1a\x11.crm.AuthResponse\x12F\n" +
	"\rValidateToken\x12\x19.crm.ValidateTokenRequest\x1a\x1a.crm.ValidateTokenResponse\x12d\n" +
	"\x17ListOrganizationsByUser\x12#.crm.ListOrganizationsByUserRequest\x1a$.crm.ListOrganizationsByUserResponseB\x1dZ\x1bgithub.com/usegro/proto/crmb\x06proto3"

var (
	file_proto_crm_crm_proto_rawDescOnce sync.Once
	file_proto_crm_crm_proto_rawDescData []byte
)

func file_proto_crm_crm_proto_rawDescGZIP() []byte {
	file_proto_crm_crm_proto_rawDescOnce.Do(func() {
		file_proto_crm_crm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_crm_crm_proto_rawDesc), len(file_proto_crm_crm_proto_rawDesc)))
	})
	return file_proto_crm_crm_proto_rawDescData
}

var file_proto_crm_crm_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_crm_crm_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_crm_crm_proto_goTypes = []any{
	(TenantStatus)(0),                       // 0: crm.TenantStatus
	(LifecycleStage)(0),                     // 1: crm.LifecycleStage
	(LeadStatus)(0),                         // 2: crm.LeadStatus
	(UserRole)(0),                           // 3: crm.UserRole
	(*Tenant)(nil),                          // 4: crm.Tenant
	(*CreateTenantRequest)(nil),             // 5: crm.CreateTenantRequest
	(*GetTenantRequest)(nil),                // 6: crm.GetTenantRequest
	(*UpdateTenantRequest)(nil),             // 7: crm.UpdateTenantRequest
	(*Contact)(nil),                         // 8: crm.Contact
	(*CreateContactRequest)(nil),            // 9: crm.CreateContactRequest
	(*GetContactRequest)(nil),               // 10: crm.GetContactRequest
	(*UpdateContactRequest)(nil),            // 11: crm.UpdateContactRequest
	(*UpsertContactByPhoneRequest)(nil),     // 12: crm.UpsertContactByPhoneRequest
	(*ListContactsRequest)(nil),             // 13: crm.ListContactsRequest
	(*ListContactsResponse)(nil),            // 14: crm.ListContactsResponse
	(*Lead)(nil),                            // 15: crm.Lead
	(*CreateLeadRequest)(nil),               // 16: crm.CreateLeadRequest
	(*UpdateLeadRequest)(nil),               // 17: crm.UpdateLeadRequest
	(*ListLeadsRequest)(nil),                // 18: crm.ListLeadsRequest
	(*ListLeadsResponse)(nil),               // 19: crm.ListLeadsResponse
	(*UpdateLifecycleStageRequest)(nil),     // 20: crm.UpdateLifecycleStageRequest
	(*User)(nil),                            // 21: crm.User
	(*CreateUserRequest)(nil),               // 22: crm.CreateUserRequest
	(*AuthenticateUserRequest)(nil),         // 23: crm.AuthenticateUserRequest
	(*AuthResponse)(nil),                    // 24: crm.AuthResponse
	(*ValidateTokenRequest)(nil),            // 25: crm.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),           // 26: crm.ValidateTokenResponse
	(*CrmOrganization)(nil),                 // 27: crm.CrmOrganization
	(*ListOrganizationsByUserRequest)(nil),  // 28: crm.ListOrganizationsByUserRequest
	(*ListOrganizationsByUserResponse)(nil), // 29: crm.ListOrganizationsByUserResponse
	nil,                                     // 30: crm.Contact.CustomFieldsEntry
	(*timestamppb.Timestamp)(nil),           // 31: google.protobuf.Timestamp
}
var file_proto_crm_crm_proto_depIdxs = []int32{
	0,  // 0: crm.Tenant.status:type_name -> crm.TenantStatus
	31, // 1: crm.Tenant.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: crm.UpdateTenantRequest.status:type_name -> crm.TenantStatus
	1,  // 3: crm.Contact.lifecycle_stage:type_name -> crm.LifecycleStage
	30, // 4: crm.Contact.custom_fields:type_name -> crm.Contact.CustomFieldsEntry
	31, // 5: crm.Contact.created_at:type_name -> google.protobuf.Timestamp
	31, // 6: crm.Contact.last_seen_at:type_name -> google.protobuf.Timestamp
	8,  // 7: crm.UpdateContactRequest.contact:type_name -> crm.Contact
	1,  // 8: crm.ListContactsRequest.lifecycle_stage:type_name -> crm.LifecycleStage
	8,  // 9: crm.ListContactsResponse.contacts:type_name -> crm.Contact
	2,  // 10: crm.Lead.status:type_name -> crm.LeadStatus
	1,  // 11: crm.Lead.lifecycle_stage:type_name -> crm.LifecycleStage
	31, // 12: crm.Lead.created_at:type_name -> google.protobuf.Timestamp
	15, // 13: crm.UpdateLeadRequest.lead:type_name -> crm.Lead
	15, // 14: crm.ListLeadsResponse.leads:type_name -> crm.Lead
	1,  // 15: crm.UpdateLifecycleStageRequest.stage:type_name -> crm.LifecycleStage
	3,  // 16: crm.User.role:type_name -> crm.UserRole
	3,  // 17: crm.CreateUserRequest.role:type_name -> crm.UserRole
	21, // 18: crm.AuthResponse.user:type_name -> crm.User
	21, // 19: crm.ValidateTokenResponse.user:type_name -> crm.User
	31, // 20: crm.CrmOrganization.created_at:type_name -> google.protobuf.Timestamp
	27, // 21: crm.ListOrganizationsByUserResponse.organizations:type_name -> crm.CrmOrganization
	5,  // 22: crm.CRMService.CreateTenant:input_type -> crm.CreateTenantRequest
	6,  // 23: crm.CRMService.GetTenant:input_type -> crm.GetTenantRequest
	7,  // 24: crm.CRMService.UpdateTenant:input_type -> crm.UpdateTenantRequest
	9,  // 25: crm.CRMService.CreateContact:input_type -> crm.CreateContactRequest
	10, // 26: crm.CRMService.GetContact:input_type -> crm.GetContactRequest
	11, // 27: crm.CRMService.UpdateContact:input_type -> crm.UpdateContactRequest
	13, // 28: crm.CRMService.ListContacts:input_type -> crm.ListContactsRequest
	12, // 29: crm.CRMService.UpsertContactByPhone:input_type -> crm.UpsertContactByPhoneRequest
	16, // 30: crm.CRMService.CreateLead:input_type -> crm.CreateLeadRequest
	17, // 31: crm.CRMService.UpdateLead:input_type -> crm.UpdateLeadRequest
	18, // 32: crm.CRMService.ListLeads:input_type -> crm.ListLeadsRequest
	20, // 33: crm.CRMService.UpdateLifecycleStage:input_type -> crm.UpdateLifecycleStageRequest
	22, // 34: crm.CRMService.CreateUser:input_type -> crm.CreateUserRequest
	23, // 35: crm.CRMService.AuthenticateUser:input_type -> crm.AuthenticateUserRequest
	25, // 36: crm.CRMService.ValidateToken:input_type -> crm.ValidateTokenRequest
	28, // 37: crm.CRMService.ListOrganizationsByUser:input_type -> crm.ListOrganizationsByUserRequest
	4,  // 38: crm.CRMService.CreateTenant:output_type -> crm.Tenant
	4,  // 39: crm.CRMService.GetTenant:output_type -> crm.Tenant
	4,  // 40: crm.CRMService.UpdateTenant:output_type -> crm.Tenant
	8,  // 41: crm.CRMService.CreateContact:output_type -> crm.Contact
	8,  // 42: crm.CRMService.GetContact:output_type -> crm.Contact
	8,  // 43: crm.CRMService.UpdateContact:output_type -> crm.Contact
	14, // 44: crm.CRMService.ListContacts:output_type -> crm.ListContactsResponse
	8,  // 45: crm.CRMService.UpsertContactByPhone:output_type -> crm.Contact
	15, // 46: crm.CRMService.CreateLead:output_type -> crm.Lead
	15, // 47: crm.CRMService.UpdateLead:output_type -> crm.Lead
	19, // 48: crm.CRMService.ListLeads:output_type -> crm.ListLeadsResponse
	15, // 49: crm.CRMService.UpdateLifecycleStage:output_type -> crm.Lead
	21, // 50: crm.CRMService.CreateUser:output_type -> crm.User
	24, // 51: crm.CRMService.AuthenticateUser:output_type -> crm.AuthResponse
	26, // 52: crm.CRMService.ValidateToken:output_type -> crm.ValidateTokenResponse
	29, // 53: crm.CRMService.ListOrganizationsByUser:output_type -> crm.ListOrganizationsByUserResponse
	38, // [38:54] is the sub-list for method output_type
	22, // [22:38] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_crm_crm_proto_init() }
func file_proto_crm_crm_proto_init() {
	if File_proto_crm_crm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_crm_crm_proto_rawDesc), len(file_proto_crm_crm_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_crm_crm_proto_goTypes,
		DependencyIndexes: file_proto_crm_crm_proto_depIdxs,
		EnumInfos:         file_proto_crm_crm_proto_enumTypes,
		MessageInfos:      file_proto_crm_crm_proto_msgTypes,
	}.Build()
	File_proto_crm_crm_proto = out.File
	file_proto_crm_crm_proto_goTypes = nil
	file_proto_crm_crm_proto_depIdxs = nil
}
